/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/29/20, 9:47 AM' 
 * Generated by 'srk00020' 
 * Generated on server 'ODAWS02-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-05%253A00&ticket=ST-82409-CtPenDdGTUnNG534mjZb-cas' 
 *
 */

/****************************************************************/
/*          S A S   S A M P L E   L I B R A R Y                 */
/*                                                              */
/*    NAME: TEMPLFT                                             */
/*   TITLE: PROC LIFETEST Template                              */
/* PRODUCT: STAT                                                */
/*  SYSTEM: ALL                                                 */
/*    KEYS: graphics, ods, survival analysis, Kaplan-Meier      */
/*   PROCS:                                                     */
/*    DATA:                                                     */
/*                                                              */
/* SUPPORT: saswfk                UPDATE: July 25, 2013         */
/*     REF: ods graphics                                        */
/*    MISC:                                                     */
/*   NOTES: This sample provides templates for the PROC         */
/*          LIFETEST survival plot that are modular and         */
/*          easier to modify than the default templates.        */
/****************************************************************/
proc template;
  define style styles.Phil;
  parent=styles.statistical;
    class fonts /
        "docfont" = ("Calibri light", 10pt)
        "tablefont" = ("Calibri light", 10pt);
    class UserText / background=white FontFamily="Calibri light" FontSize=12pt;
    class table / CellPadding=75px BorderColor=grey FontFamily="Calibri light" FontSize=12pt;
    class header / BackgroundColor=AliceBlue color=MidnightBlue FontWeight=medium FontFamily="Calibri light" FontSize=12pt; 
    class footer / BackgroundColor=grayF2 color=black FontWeight=medium FontStyle=italic FontFamily="Calibri light" FontSize=11pt; 
    class rowheader / foreground=MidnightBlue background=AliceBlue FontWeight=medium FontFamily="Calibri light" FontSize=12pt;
    class SystemTitle / FontSize=14pt FontWeight=medium FontFamily="Calibri light" color=black BackgroundColor=white                                                
                        BorderBottomColor=white BorderTopColor=white 
                        BorderRightColor=white BorderLeftColor=white;  
    class SystemFooter / FontSize=11pt FontWeight=light FontFamily="Calibri light" color=black BackgroundColor=white                                                
                         BorderBottomColor=white BorderTopColor=white 
                         BorderRightColor=white BorderLeftColor=white;  
    class PageNo from PageNo / Color=black FontSize=10pt FontWeight=medium FontStyle=roman FontFamily="Calibri light"; 
    class colors / 'proctitlefg'=black                                    
                   'proctitlebg'=white                                  
                   'docfg'=black
                   'docbg'=white
                   'bylinebg'=white 
                   'notebg'=white; 
	class GraphFonts / 'GraphDataFont' = ("Calibri light",8pt)
	                   'GraphUnicodeFont'=("Calibri light",10pt) 
                       'GraphValueFont' = ("Calibri light",10pt)
                       'GraphLabelFont' = ("Calibri light",12pt)
					   'GraphLabel2Font' = ("Calibri light",12pt)  
                       'GraphFootnoteFont' = ("Calibri light",10pt)
					   'GraphTitle1Font' = ("Calibri light",13pt) 
                       'GraphTitleFont'=("Calibri light",13pt)
                       'GraphAnnoFont'=("Calibri light",10pt);
	class data / FontFamily="Calibri light" FontSize=11pt;
	class GraphBorderLines / ContrastColor=MEGR LineThickness=2;
	*class GraphAxisLines / ContrastColor=black color=white;
	class GraphWalls / ContrastColor=black color=white;
	class GraphBackground / color=CXFFFAF6;
end;
run;

FILENAME REFFILE '/home/srk00020/SAS code/For_Analysis_Complete_Env_Project_With_Species_Names.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=WORK.IMPORT;
	GETNAMES=YES;
	SHEET="master";
RUN;

PROC CONTENTS DATA=WORK.IMPORT; RUN;


%web_open_table(WORK.IMPORT);

ods rtf file="/home/srk00020/SAS code/freq_anal.rtf" style=Phil;

proc freq data=WORK.IMPORT;
Tables (Year Season Facility Region Salmonella_serogroup1 Salmonella_serogroup2 Salmonella_serogroup3 Species)*Salmonella_Positive / norow nocol MISSPRINT;
*Tables Salmonella_Positive*(Year Season Facility Region Salmonella_serogroup1 Salmonella_serogroup2 Salmonella_serogroup3 Species) / Plots=mosaicplot norow nocol MISSPRINT;
RUN;

run;
ods rtf close;
PROC PRINT DATA=WORK.IMPORT;
RUN;
